repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # --- MUDANÇA AQUI ---
  # Usamos 'repo: local' para rodar o binário do seu sistema.
  # Isso evita o erro de compilação "invalid array length".
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        types: [go]
        language: system
        pass_filenames: false # O linter roda no projeto todo, não arquivo por arquivo

      - id: go-build
        name: go-build
        entry: go build -o tmp_check.exe ./cmd/api/main.go
        types: [go]
        language: system
        pass_filenames: false

      - id: go-test
        name: go-test
        entry: go test -v ./...
        types: [go]
        language: system
        pass_filenames: false
